# Generated by Django 5.1.1 on 2024-09-05 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ExportFile',
        ),
        migrations.AlterField(
            model_name='importfile',
            name='file',
            field=models.FileField(upload_to='imports/'),
        ),
        migrations.AddField(
            model_name='userid',
            name='imported',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.importfile'),
        ),
    ]
