# Generated by Django 5.1.1 on 2024-09-05 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userid_delete_exportfile_alter_importfile_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, upload_to='exports/')),
                ('source', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.importfile')),
            ],
        ),
        migrations.AddField(
            model_name='userid',
            name='exported',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.exportfile'),
        ),
    ]
