# Generated by Django 5.1.1 on 2024-09-06 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_exportfile_userid_exported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userid',
            name='imported',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.importfile'),
        ),
    ]
