# Generated by Django 5.1.1 on 2024-09-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userid_imported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportfile',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='exports/'),
        ),
    ]
