# Generated by Django 5.1.1 on 2024-09-07 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_exportfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportfile',
            name='file',
            field=models.FileField(default=None, upload_to='exports/'),
        ),
        migrations.AlterField(
            model_name='userid',
            name='exported',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.exportfile'),
        ),
    ]
